config/routes.rb
Rails.application.routes.draw do
  resources :stock_transfers
  resources :po_receipts
  resources :schools
  resources :po_items
  resources :purchase_orders
  get 'purchase_orders/fullfill/:id', to: 'purchase_orders#fullfill', as: 'fullfill_purchase_order'
  resources :employees
  resources :stocks
  resources :warehouses
  resources :suplies
  resources :budget_items
  root 'dashboard#index'
  devise_for :users, controllers: { sessions: 'users/sessions' }  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/employee.rb
class Employee < ApplicationRecord

  def self.ransackable_associations(auth_object = nil)
    []
  end

  def self.ransackable_attributes(auth_object = nil)
    ["clock_num", "comp_amount", "compensations", "created_at", "delegacion", "email", "id", "id_value", "labor", "name", "phone", "role", "salary", "salary_level", "status", "updated_at"]
  end
  
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: %i[ show edit update destroy ]

  # GET /employees or /employees.json
  def index
    # @employees = Employee.all
    @q = Employee.ransack(params[:q])
    @employees = @q.result(distinct: true)
    @pagy, @employee = pagy(@q.result, items: 30 )
  end

  # GET /employees/1 or /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees or /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to employee_url(@employee), notice: "Employee was successfully created." }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1 or /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to employee_url(@employee), notice: "Employee was successfully updated." }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1 or /employees/1.json
  def destroy
    @employee.destroy!

    respond_to do |format|
      format.html { redirect_to employees_url, notice: "Employee was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def employee_params
      params.require(:employee).permit(:name, :email, :phone, :clock_num, :role, :salary_level, :delegacion, :compensations, :comp_amount, :status, :salary, :labor)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_employee.html.erb
<div id="<%= dom_id employee %>">
  <p>
    <strong>Name:</strong>
    <%= employee.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= employee.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= employee.phone %>
  </p>

  <p>
    <strong>Clock num:</strong>
    <%= employee.clock_num %>
  </p>

  <p>
    <strong>Role:</strong>
    <%= employee.role %>
  </p>

  <p>
    <strong>Salary level:</strong>
    <%= employee.salary_level %>
  </p>

  <p>
    <strong>Delegacion:</strong>
    <%= employee.delegacion %>
  </p>

  <p>
    <strong>Compensations:</strong>
    <%= employee.compensations %>
  </p>

  <p>
    <strong>Comp amount:</strong>
    <%= employee.comp_amount %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= employee.status %>
  </p>

  <p>
    <strong>Salary:</strong>
    <%= employee.salary %>
  </p>

  <p>
    <strong>Labor:</strong>
    <%= employee.labor %>
  </p>

</div>

app/views/employees/_employees_table.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="card p-3">
      <div class="d-flex justify-content-between">
        <div>
            <%= link_to "Agregar Empleado", new_employee_path, class:'btn btn-primary' %>
        </div>
        <div>
            <%== pagy_bootstrap_nav(@pagy) %>
        </div>
        <div>
        <%= search_form_for @q do |e| %>
                <%= e.label "Nombre" %>
                <%= e.search_field :name_cont %>
                <%= e.label "Delegación" %>
                <%= e.search_field :delegacion_cont %>
                <%= e.submit class:'btn btn-info' %>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<p></p>

<table class= "table_1 table-striped_1">
    <thead class="table-dark_1">
        <th><%= sort_link(@q, :id, default_order: :asc, class:'text-white text-decoration-none') %></th>
        <th><%= sort_link(@q, :name, class:'text-white text-decoration-none') %></th>
        <th>Teléfono</th>
        <th>Checador</th>
        <th>Jornada</th>
        <th><%= sort_link(@q, :delegacion, class:'text-white text-decoration-none') %></th>
        <th>Detalles</th>
        <th>Modificar</th>
    </thead>
    <tbody>
        <% @employees.each do |e| %>
        <tr>
            <td><%= e.id %></td>
            <td><%= e.name %></td>
            <td><%= e.phone %></td>
            <td><%= e.clock_num %></td>
            <td><%= e.labor %></td>
            <td><%= e.delegacion %></td>
            <td style="text-align:left;"><%= link_to employee_path(e), title: 'Detalles' do %>
                <i class="ps-6 bi-eye"></i>
            <% end %>
            </td>
            <td style="text-align:left;"><%= link_to edit_employee_path(e), title: 'Modificar' do %>
                <i class="ps-6 bi-pencil"></i>
            <% end %>
            </td>
        </tr>
<% end %>
    </tbody>
            
</table>

app/views/employees/_form.html.erb
<%= simple_form_for(@employee) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :email %>
    <%= f.input :phone %>
    <%= f.input :clock_num %>
    <%= f.input :role %>
    <%= f.input :salary_level %>
    <%= f.input :delegacion %>
    <%= f.input :compensations %>
    <%= f.input :comp_amount %>
    <%= f.input :status %>
    <%= f.input :salary %>
    <%= f.input :labor %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing employee</h1>

<%= render "form", employee: @employee %>

<br>

<div>
  <%= link_to "Show this employee", @employee %> |
  <%= link_to "Back to employees", employees_path %>
</div>

app/views/employees/index.html.erb
<p style="color: green"><%= notice %></p>

<h1><%= link_to "Empleados", employees_path, class:'text-black text-decoration-none' %></h1>

<div id="employees">
<%= render 'employees_table' %>
</div>

app/views/employees/new.html.erb
<h1>New employee</h1>

<%= render "form", employee: @employee %>

<br>

<div>
  <%= link_to "Back to employees", employees_path %>
</div>

app/views/employees/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @employee %>

<div>
  <%= link_to "Edit this employee", edit_employee_path(@employee) %> |
  <%= link_to "Back to employees", employees_path %>

  <%= button_to "Destroy this employee", @employee, method: :delete %>
</div>