config/routes.rb
Rails.application.routes.draw do
  resources :stock_transfers
  resources :po_receipts
  resources :schools
  resources :po_items
  resources :purchase_orders
  get 'purchase_orders/fullfill/:id', to: 'purchase_orders#fullfill', as: 'fullfill_purchase_order'
  resources :employees
  resources :stocks
  resources :warehouses
  resources :suplies
  resources :budget_items
  root 'dashboard#index'
  devise_for :users, controllers: { sessions: 'users/sessions' }  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/budget_item.rb
class BudgetItem < ApplicationRecord
  has_many :suplies
  has_many :purchase_orders
  has_many :po_items, through: :purchase_orders

  enum update_type: [:ministracion, :gasto, :adecuacion, :ampliación]
  after_initialize :set_default_update_type, :if => :new_record?

  def set_default_update_type
    self.update_type ||= :ministracion
  end

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "descripcion", "id", "id_value", "last_updated", "monto_disp", "partida", "update_type", "updated_at"]
  end

  def self.ransackable_associations(auth_object = nil)
    []
  end

end

app/controllers/budget_items_controller.rb
class BudgetItemsController < ApplicationController
  before_action :set_budget_item, only: %i[ show edit update destroy ]

  # GET /budget_items or /budget_items.json
  def index
    # @budget_items = BudgetItem.all
    @q = BudgetItem.ransack(params[:q])
    @budget_items = @q.result(distinct: true)
    @pagy, @budget_items = pagy(@q.result, items: 30 )
  end

  # GET /budget_items/1 or /budget_items/1.json
  def show
  end

  # GET /budget_items/new
  def new
    @budget_item = BudgetItem.new
  end

  # GET /budget_items/1/edit
  def edit
  end

  # POST /budget_items or /budget_items.json
  def create
    @budget_item = BudgetItem.new(budget_item_params)

    respond_to do |format|
      if @budget_item.save
        format.html { redirect_to budget_item_url(@budget_item), notice: "Budget item was successfully created." }
        format.json { render :show, status: :created, location: @budget_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @budget_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /budget_items/1 or /budget_items/1.json
  def update
    respond_to do |format|
      if @budget_item.update(budget_item_params)
        format.html { redirect_to budget_item_url(@budget_item), notice: "Budget item was successfully updated." }
        format.json { render :show, status: :ok, location: @budget_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @budget_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /budget_items/1 or /budget_items/1.json
  def destroy
    @budget_item.destroy!

    respond_to do |format|
      format.html { redirect_to budget_items_url, notice: "Budget item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_budget_item
      @budget_item = BudgetItem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def budget_item_params
      params.require(:budget_item).permit(:partida, :descripcion, :monto_disp, :last_updated, :update_type)
    end
end

app/helpers/budget_items_helper.rb
module BudgetItemsHelper
end

app/views/budget_items/_budget_item.html.erb
<div id="<%= dom_id budget_item %>">
  <p>
    <strong>Partida:</strong>
    <%= budget_item.partida %>
  </p>

  <p>
    <strong>Descripcion:</strong>
    <%= budget_item.descripcion %>
  </p>

  <p>
    <strong>Monto disp:</strong>
    <%= budget_item.monto_disp %>
  </p>

  <p>
    <strong>Last updated:</strong>
    <%= budget_item.last_updated %>
  </p>

  <p>
    <strong>Update type:</strong>
    <%= budget_item.update_type %>
  </p>

</div>

app/views/budget_items/_budget_items_table.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="card p-3">
      <div class="d-flex justify-content-between">
        <div>
            <%= link_to "Crear Partida", new_budget_item_path, class:'btn btn-primary' %>
        </div>
        <div>
            <%== pagy_bootstrap_nav(@pagy) %>
        </div>
        <div>
            <%= search_form_for @q do |s| %>
                <%= s.label :partida %>
                <%= s.search_field :partida_eq %>
                <%= s.label :descripcion %>
                <%= s.search_field :descripcion_cont %>
                <%= s.submit class:'btn btn-info' %>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<p></p>

<table class= "table_1 table-striped_1">
    <thead class="table-dark_1">
        <tr>
            <th>ID</th>
            <th>Partida</th>
            <th>Descripción</th>
            <th>Monto Disponible</th>
            <th>Última Edición</th>
            <th>Tipo de modificación</th>
            <th>Detalles</th>
            <th>Modificar</th>
        </tr>
    </thead>
    
    <tbody>
    <% @budget_items.each do |bi| %>
        <tr>
            <td><%= bi.id %></td>
            <td><%= bi.partida %></td>
            <td><%= bi.descripcion %></td>
            <td><%= number_to_currency(bi.monto_disp) %></td>
            <td><%= bi.last_updated %></td>
            <td><%= bi.update_type %></td>
            <td style="text-align: left"><%= link_to budget_item_path(bi), title: 'Ver Detalle' do %>
                <i class= "fs-6 bi-eye"></i>
            <% end %>
            </td>
            <td style="text-align: left"><%= link_to edit_budget_item_path(bi), title: 'Editar' do %>
                <i class= "fs-6 bi-pencil"></i>
            <% end %>
            </td>
        </tr>
    <% end %>
    </tbody>
</table>

app/views/budget_items/_form.html.erb
<%= simple_form_for(@budget_item) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :partida %>
    <%= f.input :descripcion %>
    <%= f.input :monto_disp %>
    <%= f.input :last_updated %>
    <%= f.input :update_type, collection: BudgetItem.update_types.keys %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class:'btn btn-primary' %>
  </div>
<% end %>

app/views/budget_items/edit.html.erb
<h1>Modificar Partida</h1>

<%= render "form", budget_item: @budget_item %>

<br>

<div>
  <%= link_to "Detalles", @budget_item, class:'btn btn-info' %> |
  <%= link_to "Regresar", budget_items_path, class:'btn btn-info' %>
</div>

app/views/budget_items/index.html.erb
<p style="color: green"><%= notice %></p>
<h1><%= link_to "Partidas", budget_items_path, class:'text-black text-decoration-none' %></h1>

<div id="budget_items">
  <%= render 'budget_items_table' %>
</div>

app/views/budget_items/new.html.erb
<h1>Crear Partida</h1>

<%= render "form", budget_item: @budget_item %>

<br>

<div>
  <%= link_to "Regresar", budget_items_path, class:'btn btn-info' %>
</div>

app/views/budget_items/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @budget_item %>

<div>
  <%= link_to "Editar partida", edit_budget_item_path(@budget_item), class:'btn btn-info' %> |
  <%= link_to "Regresar", budget_items_path, class:'btn btn-info' %>
<p></p>
  <%= button_to "Borrar", @budget_item, method: :delete, class:'btn btn-danger' %>
</div>