config/routes.rb
Rails.application.routes.draw do
  resources :stock_transfers
  resources :po_receipts
  resources :schools
  resources :po_items
  resources :purchase_orders
  get 'purchase_orders/fullfill/:id', to: 'purchase_orders#fullfill', as: 'fullfill_purchase_order'
  resources :employees
  resources :stocks
  resources :warehouses
  resources :suplies
  resources :budget_items
  root 'dashboard#index'
  devise_for :users, controllers: { sessions: 'users/sessions' }  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/budget_item.rb
class BudgetItem < ApplicationRecord
  has_many :suplies
  has_many :purchase_orders
  has_many :po_items, through: :purchase_orders

  enum update_type: [:ministracion, :gasto, :adecuacion, :ampliación]
  after_initialize :set_default_update_type, :if => :new_record?

  def set_default_update_type
    self.update_type ||= :ministracion
  end

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "descripcion", "id", "id_value", "last_updated", "monto_disp", "partida", "update_type", "updated_at"]
  end

  def self.ransackable_associations(auth_object = nil)
    []
  end

end

app/models/employee.rb
class Employee < ApplicationRecord

  def self.ransackable_associations(auth_object = nil)
    []
  end

  def self.ransackable_attributes(auth_object = nil)
    ["clock_num", "comp_amount", "compensations", "created_at", "delegacion", "email", "id", "id_value", "labor", "name", "phone", "role", "salary", "salary_level", "status", "updated_at"]
  end
  
end

app/models/po_item.rb
class PoItem < ApplicationRecord
  belongs_to :purchase_order
  belongs_to :suply

  enum status: [:creada, :recibida]
  after_initialize :set_default_status, :if => :new_record?

  def set_default_status
    self.status ||= :creada
  end

  def self.ransackable_associations(auth_object = nil)
    ["purchase_order", "suply"]
  end

  def ped_total
    suply.costo_u * self.qty_ped
  end

  def spent
    self.new_cost * self.qty_recib
  end
end

app/models/po_receipt.rb
class PoReceipt < ApplicationRecord
  belongs_to :purchase_order
  belongs_to :suply
  belongs_to :warehouse
  belongs_to :user

  def self.ransackable_associations(auth_object = nil)
    ["purchase_order", "suply", "user", "warehouse"]
  end

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "id", "id_value", "new_cost", "proveedor", "purchase_order_id", "qty", "suply_id", "updated_at", "user_id", "warehouse_id"]
  end

end

app/models/purchase_order.rb
class PurchaseOrder < ApplicationRecord
  belongs_to :budget_item
  belongs_to :user
  has_many :po_items, dependent: :destroy
  accepts_nested_attributes_for :po_items, allow_destroy: true

  enum status: [:creada, :cotizada, :recibida]
  after_initialize :set_default_status, :if => :new_record?

  def set_default_status
    self.status ||= :creada
  end

  def self.ransackable_associations(auth_object = nil)
    ["budget_item", "user"]
  end

  def self.ransackable_attributes(auth_object = nil)
    ["budget_item_id", "created_at", "date", "status", "updated_at", "user_id"]
  end

  def pre_spent
    self.po_items.sum(:ped_total)
  end

  def total_spent
    self.po_items.sum(:new_cost)
  end

end

app/models/school.rb
class School < ApplicationRecord

  def self.ransackable_attributes(auth_object = nil)
    ["ambito", "calle", "cct", "colonia", "created_at", "detalle", "docentes", "entre_calle", "id", "id_value", "latitud", "localidad", "longitud", "matricula", "municipio", "nivel", "nombre", "numero", "p_de_apoyo", "sector", "subnivel", "turno", "updated_at", "y_calle", "zona_esc"]
  end
  
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :suply
  belongs_to :warehouse

  enum update_type: [:entrada, :salida, :ajuste, :transferencia]
  after_initialize :set_default_update_type, :if => :new_record?

  def set_default_update_type
    self.update_type ||= :ajuste
  end

  def self.ransackable_associations(auth_object = nil)
    ["suply", "warehouse"]
  end

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "id", "id_value", "last_updated", "qty", "suply_id", "update_type", "updated_at", "warehouse_id"]
  end

end

app/models/stock_transfer.rb
class StockTransfer < ApplicationRecord
  belongs_to :suply
  belongs_to :user
  belongs_to :warehouse, :foreign_key => 'warehouse_out'

  def self.ransackable_associations(auth_object = nil)
    ["suply", "user"]
  end

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "id", "id_value", "qty", "suply_id", "updated_at", "user_id", "warehouse_in", "warehouse_out"]
  end

end

app/models/suply.rb
class Suply < ApplicationRecord
  belongs_to :budget_item
  has_many :stocks

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "descripcion", "id", "id_value", "last_updated", "monto_disp", "partida", "update_type", "updated_at", "prev_cost"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["budget_item"]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :stock_transfers
  has_many :purchase_orders

  enum role: [:visitante, :despachador, :almacenista, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
      self.role ||= :visitante
  end

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email", "encrypted_password", "id", "id_value", "remember_created_at", "reset_password_sent_at", "reset_password_token", "role", "updated_at", "username"]
  end

end

app/models/warehouse.rb
class Warehouse < ApplicationRecord

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "delegacion", "id", "id_value", "nombre", "tipo", "ubicacion", "updated_at"]
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/po_items_helper.rb
module PoItemsHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/suplies_helper.rb
module SupliesHelper
end

app/helpers/warehouses_helper.rb
module WarehousesHelper
end

app/views/shared/_session_manager.html.erb
<% if current_user %>
                <div class="dropdown pb-4">
                    <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="fs-3 bi bi-person-circle"></i>
                        <span class="d-none d-sm-inline mx-1"><%= current_user.username %></span>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-dark text-small shadow">
                        <li><%= link_to "Editar cuenta", edit_user_registration_path, class:'dropdown-item' %></li>
                        <li><a class="dropdown-item" href="#">Settings</a></li>
                        <li><a class="dropdown-item" href="#">Profile</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><%= button_to "Cerrar sesión", destroy_user_session_path, method: :delete, class: 'dropdown-item' %></li>
                    </ul>
                </div>
                <span>
                    Perfil: <%= current_user.role.to_s.humanize %>
                </span>
<% else %>
    <div class="dropdown pb-4">
                    <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="fs-3 bi bi-person-circle"></i>
                        <span class="d-none d-sm-inline mx-1">Control de acceso</span>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-dark text-small shadow">
                        <li><%= link_to "Iniciar sesión", new_user_session_path, class:'dropdown-item' %></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><%= link_to "Registrar usuario", new_user_registration_path, class: 'dropdown-item' %></li>
                    </ul>
                </div>
<% end %>

app/views/shared/_sidebar.html.erb
<% if current_user %>
    <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
        <a class="sidebar-brand d-flex justify-content-center" href="<%= root_path %>">
                <div class="sidebar-brand-icon mt-3 mb-10 text-center">
                    <img src="<%= asset_path( 'Logo.648cc722.png' ) %>" width="245">
                </div>
        </a>

            <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
                <li class="nav-item text-center"><b>SIME</b><br />Sistema Integral de Mantenimiento Escolar</li>
                <li class="nav-item">
                        <i class="fs-4 bi-speedometer2"></i> <span class=""><%= link_to "Dashboard", root_path, class:'ms-1 d-none d-sm-inline nav-link_1 align-middle px-0' %></span>
                </li>
                <li>
                    <a href="#submenu1" data-bs-toggle="collapse" class="nav-link_1 px-0 align-middle">
                        <i class="fs-4 bi-list-columns-reverse"></i> <span class="ms-1 d-none d-sm-inline">Catálogos</span> </a>
                    <ul class="collapse nav flex-column ms-1" id="submenu1" data-bs-parent="#menu">
                        <li class="w-100">
                            <span><%= link_to "Suministros", suplies_path, class:'d-none d-sm-inline nav-link_1 px-0' %></span>
                        </li>
                        <li class="w-100">
                            <span><%= link_to "Escuelas", schools_path, class:'d-none d-sm-inline nav-link_1 px-0' %></span>
                        </li>
                        
                        <li class="w-100">
                            <span><%= link_to "Empleados", employees_path, class:'d-none d-sm-inline nav-link_1 px-0' %></span>
                        </li>
                        <li class="w-100">
                            <span><%= link_to "Presupuesto", budget_items_path, class:'d-none d-sm-inline nav-link_1 px-0' %></span>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#" class="nav-link_1 px-0 align-middle">
                        <i class="fs-4 bi-backpack2"></i> <span class="ms-1 d-none d-sm-inline">Otros</span></a>
                </li>
                <li>
                    <a href="#submenu2" data-bs-toggle="collapse" class="nav-link_1 px-0 align-middle ">
                        <i class="fs-4 bi-arrows-move"></i> <span class="ms-1 d-none d-sm-inline">Movimientos</span></a>
                    <ul class="collapse nav flex-column ms-1" id="submenu2" data-bs-parent="#menu">
                        <li class="w-100">
                            <span><%= link_to "Órdenes de Compra", purchase_orders_path, class:'d-none d-sm-inline nav-link_1 px-0' %></span>
                        </li>
                        <li class="w-100">
                            <span><%= link_to "Recibo", po_receipts_path, class:'d-none d-sm-inline nav-link_1 px-0' %></span>
                        </li>
                        <li class="w-100">
                            <span><%= link_to "Transferencias", stock_transfers_path, class:'d-none d-sm-inline nav-link_1 px-0' %></span>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#submenu3" data-bs-toggle="collapse" class="nav-link_1 px-0 align-middle">
                        <i class="fs-4 bi-grid"></i> <span class="ms-1 d-none d-sm-inline">Otras cosas</span> </a>
                        <ul class="collapse nav flex-column ms-1" id="submenu3" data-bs-parent="#menu">
                            <li class="w-100">
                                <span><%= link_to "Existencias", stocks_path, class:"nav-link_1 px-0 d-none d-sm-inline" %></span>
                            </li>
                            <li>
                                <span><%= link_to "Almacenes", warehouses_path, class:"nav-link_1 px-0 d-none d-sm-inline" %></span>
                            </li>
                            <li>
                                <a href="#" class="nav-link_1 px-0"> <span class="d-none d-sm-inline">Otros 3</span></a>
                            </li>
                        </ul>
            </li>
            <li>
                <a href="/employees" class="nav-link_1 px-0 align-middle">
                    <i class="fs-4 bi-people"></i> <span class="ms-1 d-none d-sm-inline">Personas</span> </a>
            </li>
        </ul>
   
        <hr/>
            <div class="dropdown mb-5">
                <%= render 'shared/session_manager' %>
            </div>
    </div>
<% else %>
    <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
        <a class="sidebar-brand d-flex justify-content-center" href="<%= root_path %>">
                <div class="sidebar-brand-icon mt-3 mb-10 text-center">
                    <img src="<%= asset_path( 'Logo.648cc722.png' ) %>" width="245">
                </div>
        </a>

            <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
                <li class="nav-item text-center"><b>SIME</b><br />Sistema Integral de Mantenimiento Escolar</li>
            </ul>
   
        <hr/>
            <div class="dropdown mb-5">
                <%= render 'shared/session_manager' %>
            </div>
    </div>
<% end %>