config/routes.rb
Rails.application.routes.draw do
  resources :stock_transfers
  resources :po_receipts
  resources :schools
  resources :po_items
  resources :purchase_orders
  get 'purchase_orders/fullfill/:id', to: 'purchase_orders#fullfill', as: 'fullfill_purchase_order'
  resources :employees
  resources :stocks
  resources :warehouses
  resources :suplies
  resources :budget_items
  root 'dashboard#index'
  devise_for :users, controllers: { sessions: 'users/sessions' }  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/school.rb
class School < ApplicationRecord

  def self.ransackable_attributes(auth_object = nil)
    ["ambito", "calle", "cct", "colonia", "created_at", "detalle", "docentes", "entre_calle", "id", "id_value", "latitud", "localidad", "longitud", "matricula", "municipio", "nivel", "nombre", "numero", "p_de_apoyo", "sector", "subnivel", "turno", "updated_at", "y_calle", "zona_esc"]
  end
  
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :set_school, only: %i[ show edit update destroy ]

  # GET /schools or /schools.json
  def index
    # @schools = School.all
    @q = School.ransack(params[:q])
    @schools = @q.result(distinct: true)
    @pagy, @schools = pagy(@q.result, items: 30 )

  end

  # GET /schools/1 or /schools/1.json
  def show
  end

  # GET /schools/new
  def new
    @school = School.new
  end

  # GET /schools/1/edit
  def edit
  end

  # POST /schools or /schools.json
  def create
    @school = School.new(school_params)

    respond_to do |format|
      if @school.save
        format.html { redirect_to school_url(@school), notice: "School was successfully created." }
        format.json { render :show, status: :created, location: @school }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schools/1 or /schools/1.json
  def update
    respond_to do |format|
      if @school.update(school_params)
        format.html { redirect_to school_url(@school), notice: "School was successfully updated." }
        format.json { render :show, status: :ok, location: @school }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1 or /schools/1.json
  def destroy
    @school.destroy!

    respond_to do |format|
      format.html { redirect_to schools_url, notice: "School was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school
      @school = School.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def school_params
      params.require(:school).permit(:cct, :nombre, :turno, :nivel, :subnivel, :detalle, :matricula, :docentes, :p_de_apoyo, :calle, :numero, :entre_calle, :y_calle, :colonia, :municipio, :localidad, :ambito, :zona_esc, :sector, :latitud, :longitud)
    end
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/schools/_form.html.erb
<%= simple_form_for(@school) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :cct %>
    <%= f.input :nombre %>
    <%= f.input :turno %>
    <%= f.input :nivel %>
    <%= f.input :subnivel %>
    <%= f.input :detalle %>
    <%= f.input :matricula %>
    <%= f.input :docentes %>
    <%= f.input :p_de_apoyo %>
    <%= f.input :calle %>
    <%= f.input :numero %>
    <%= f.input :entre_calle %>
    <%= f.input :y_calle %>
    <%= f.input :colonia %>
    <%= f.input :municipio %>
    <%= f.input :localidad %>
    <%= f.input :ambito %>
    <%= f.input :zona_esc %>
    <%= f.input :sector %>
    <%= f.input :latitud %>
    <%= f.input :longitud %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/schools/_school.html.erb
<div id="<%= dom_id school %>">
  <p>
    <strong>Cct:</strong>
    <%= school.cct %>
  </p>

  <p>
    <strong>Nombre:</strong>
    <%= school.nombre %>
  </p>

  <p>
    <strong>Turno:</strong>
    <%= school.turno %>
  </p>

  <p>
    <strong>Nivel:</strong>
    <%= school.nivel %>
  </p>

  <p>
    <strong>Subnivel:</strong>
    <%= school.subnivel %>
  </p>

  <p>
    <strong>Detalle:</strong>
    <%= school.detalle %>
  </p>

  <p>
    <strong>Matricula:</strong>
    <%= school.matricula %>
  </p>

  <p>
    <strong>Docentes:</strong>
    <%= school.docentes %>
  </p>

  <p>
    <strong>P de apoyo:</strong>
    <%= school.p_de_apoyo %>
  </p>

  <p>
    <strong>Calle:</strong>
    <%= school.calle %>
  </p>

  <p>
    <strong>Numero:</strong>
    <%= school.numero %>
  </p>

  <p>
    <strong>Entre calle:</strong>
    <%= school.entre_calle %>
  </p>

  <p>
    <strong>Y calle:</strong>
    <%= school.y_calle %>
  </p>

  <p>
    <strong>Colonia:</strong>
    <%= school.colonia %>
  </p>

  <p>
    <strong>Municipio:</strong>
    <%= school.municipio %>
  </p>

  <p>
    <strong>Localidad:</strong>
    <%= school.localidad %>
  </p>

  <p>
    <strong>Ambito:</strong>
    <%= school.ambito %>
  </p>

  <p>
    <strong>Zona esc:</strong>
    <%= school.zona_esc %>
  </p>

  <p>
    <strong>Sector:</strong>
    <%= school.sector %>
  </p>

  <p>
    <strong>Latitud:</strong>
    <%= school.latitud %>
  </p>

  <p>
    <strong>Longitud:</strong>
    <%= school.longitud %>
  </p>

</div>

app/views/schools/_schools_table.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="card p-3">
      <div class="d-flex justify-content-between">
        <div>
            <%= link_to "Crear Escuela", new_school_path, class:'btn btn-primary' %>
        </div>
        <div>
            <%== pagy_bootstrap_nav(@pagy) %>
        </div>
        <div>
            <%= search_form_for @q do |es| %>
                <%= es.label :cct %>
                <%= es.search_field :cct_cont %>
                <%= es.label :nombre %>
                <%= es.search_field :nombre_cont %>
                <%#= es.label :localidad %>
                <%#= es.search_field :localidad_cont %>
                <%= es.label :municipio %>
                <%= es.search_field :municipio_cont %>
                <%= es.submit class:'btn btn-info' %>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<p></p>

<table class= "table_1 table-striped_1">
    <thead class="table-dark_1">
    <tr>
        <th><%= sort_link(@q, :id, default_order: :asc, class:'text-white text-decoration-none') %></th>
        <th><%= sort_link(@q, :cct, class:'text-white text-decoration-none') %></th>
        <th><%= sort_link(@q, :nombre, class:'text-white text-decoration-none') %></th>
        <th><%= sort_link(@q, :localidad, class:'text-white text-decoration-none') %></th>
        <th><%= sort_link(@q, :municipio, class:'text-white text-decoration-none') %></th>
        <th></th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    <% @schools.each do |esc| %>
        <tr>
        <td><%= esc.id %></td>
        <td><%= esc.cct %></td>
        <td><%= esc.nombre %></td>
        <td><%= esc.localidad %></td>
        <td><%= esc.municipio %></td>
        <td style="text-align: center"><%= link_to school_path(esc), title: 'Ver Detalle' do %>
                <i class= "fs-6 bi-eye"></i>
            <% end %>
            </td>
        <td style="text-align: center"><%= link_to edit_school_path(esc), title: 'Editar' do %>
                <i class= "fs-6 bi-pencil"></i>
            <% end %>
        </td>
        </tr>
    <% end %>
    </tbody>
</table>

app/views/schools/edit.html.erb
<h1>Editing school</h1>

<%= render "form", school: @school %>

<br>

<div>
  <%= link_to "Show this school", @school %> |
  <%= link_to "Back to schools", schools_path %>
</div>

app/views/schools/index.html.erb
<p style="color: green"><%= notice %></p>

<h1><%= link_to "Escuelas", schools_path, class:'text-black text-decoration-none' %></h1>


<div id="schools">
<%= render 'schools_table' %>
</div>

app/views/schools/new.html.erb
<h1>New school</h1>

<%= render "form", school: @school %>

<br>

<div>
  <%= link_to "Back to schools", schools_path %>
</div>

app/views/schools/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @school %>

<div>
  <%= link_to "Edit this school", edit_school_path(@school) %> |
  <%= link_to "Back to schools", schools_path %>

  <%= button_to "Destroy this school", @school, method: :delete %>
</div>